var res = {
    bomba_png : "res/bomba.png",
    conejo_png : "res/conejo.png",
    conejo2_png : "res/conejo2.png",
    conejo3_png : "res/conejo3.png",
    fondo_png : "res/fondo.png",
    fondo2_png : "res/fondofalso.png",
    jugar1_png : "res/jugar1.png",
    jugar2_png : "res/jugar2.png",
    ayuda1_png : "res/ayuda1.png",
    ayuda2_png : "res/ayuda2.png",
    creditos1_png : "res/creditos1.png",
    creditos2_png : "res/credito2.png",
    titulo_png : "res/Titulo.png",
    zanahoria_png: "res/zanahoria.png",
    vida_png: "res/Heart.png",
    explosion_plist:"res/explosion.plist",
    czanahora_plist:"res/colzanahoria.plist",
    gameover_png:"res/gameover.png",
    fondo3_png:"res/lose.png",
    reiniciar1_png : "res/reiniciar1.png",
    reiniciar2_png : "res/reiniciar2.png",
    salir1_png : "res/salir1.png",
    salir2_png : "res/salir2.png",
    puntos_png : "res/puntaje.png",
    czanahoria_png:"res/colzanahoria.png",
    explosion_png:"res/explosion.png",
    explosion_wav:"res/Music/explosion.wav",
    point_wav:"res/Music/point.wav",
    gameover_ogg: "res/Music/game_over.ogg",
    temaFondo_mp3: "res/Music/Wagon Wheel - Electronic.mp3", 
    temaJugar_mp3:"res/Music/golucky.mp3",
    temaPower_mp3:"res/Music/Zero 8-bit.mp3",
    estrella_png:"res/estrella.png",
    power_plist:"res/power.plist",
};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}
